server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
spring:
  application:
    name: managerService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhaobao?serverTimezone=GMT
    username: root
    password: root
mybatis:
  type-aliases-package: com.zhaobao.common.pojo
  mapper-locations: classpath:com/zhaobao/common/mapper/*.xml
